image: python:3.7.5-buster

stages:
  - wololo
  - black
  - test

before_script:
  - python --version
  - pip install -r requirements.txt

wololo:
  stage: wololo
  script:
    - echo "wololo"
    - echo "Now you are blue."
  only:
    - master

black:
  stage: black
  script:
    - black -l 79 .

test:
  stage: test
  script:
    - pytest
